### ISSUE TITLE
Problem: Can't find crate

### ISSUE THREAD

**Issue by blyxyas** [nathom/youchoose#10]
VS Code gave me this error: 
failed to run custom build command for `ncurses v5.101.0`
Currently only `youchoose` is in the dependencies section, what's happening? I'm using Windows

**Comment by Blyxyas** [comment]
I found the solution, `ncurses` doesn't support Windows, I'll try with `pancurses`, which supports Windows and Unix

**Comment by blyxyas** [comment]
I found the problem, `ncurses` doesn't support Windows, there's alternatives, but you'll have to change the crate to work with [`pancurses`](https://github.com/ihalila/pancurses)
